### ISSUE TITLE
Find out more about MINCE for GEMDOS on the Atari ST

### ISSUE THREAD

**Issue by johnsonjh** [johnsonjh/pmince#22]
```text
23-Apr-85 14:02:57-MST,630;000000000000
Return-Path: <@MIT-MC:Hess.Unicorn@MIT-MULTICS.ARPA>
Received: from MIT-MC by SIMTEL20.ARPA with TCP; Tue 23 Apr 85 14:02:29-MST
Received: from MIT-MULTICS.ARPA by MIT-MC.ARPA; 23 APR 85 15:54:40 EST
Date:  Mon, 22 Apr 85 20:47 EST
From:  Hess@MIT-MULTICS.ARPA
Subject:  Oops...
To:  amethyst-users@MIT-MC.ARPA
Message-ID:  <850423014711.113316@MIT-MULTICS.ARPA>

I forgot to tell you all that MINCE is up and running on the Atari ST
series under Gem DOS.  We have tested it on the 520 but not the smaller
one (130?)  yet.  Usual price, but source won't be supplied until the
compiler/library/ROMs settle.

Brian
```

**Comment by jhjv** [comment]
![Screenshot from 2021-04-12 19-23-39](https://user-images.githubusercontent.com/79816452/114474970-557c3c80-9bc5-11eb-9140-72a816054550.png)
![Screenshot from 2021-04-12 19-24-11](https://user-images.githubusercontent.com/79816452/114474977-59a85a00-9bc5-11eb-9f66-5bd487f0baee.png)

**Comment by jhjv** [comment]
`Mince V2.63 - Copyright (c) 1980,1981,1985 Mark of the Unicorn, Inc.`

Adding to the repo... need to figure out the changes.  First I've seen >2.6 also.

**Comment by johnsonjh** [comment]
Added!

https://github.com/johnsonjh/pmince/tree/master/mincegem

**Comment by johnsonjh** [comment]
Also, from the **Atari ST Developer Kit**

![Screenshot from 2021-04-12 20-41-13](https://user-images.githubusercontent.com/61629094/114479959-14018680-9bf1-11eb-8dfe-273c7a88fdf0.png)

**Comment by johnsonjh** [comment]
Added all info to repo, closing for now, any new original research will be added to notes.
